# Autogenerated wrapper script for liblinear_jll for i686-w64-mingw32
export liblinear, predict, train

JLLWrappers.@generate_wrapper_header("liblinear")
JLLWrappers.@declare_library_product(liblinear, "liblinear.dll")
JLLWrappers.@declare_executable_product(predict)
JLLWrappers.@declare_executable_product(train)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblinear,
        "bin\\liblinear.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        predict,
        "bin\\predict.exe",
    )

    JLLWrappers.@init_executable_product(
        train,
        "bin\\train.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
